### ISSUE TITLE
Google Search sponsored phishing website

### ISSUE THREAD

**Issue by msokk** [Homebrew/brew.sh#1022]
Hi,

I wanted to notify you that currently searching for "homebrew" on Google returns a sponsored ad that has seems to point to correct domain but actually goes to a phishing website https://homebrew.mom.

Instead of the usual snippet there is a mac installer download. Not sure what it does, as it was my colleague who fell for the phishing.

<img width="567" alt="google" src="https://github.com/Homebrew/brew.sh/assets/231978/bc2f8067-4e52-449b-9227-5393464872e7">
<img width="567" alt="website" src="https://github.com/Homebrew/brew.sh/assets/231978/1dfbc7da-b847-4967-be13-3caf844b8be3">
<img width="567" alt="installer" src="https://github.com/Homebrew/brew.sh/assets/231978/528f99c6-83b3-43da-aa8f-3d2bb3f22462">
<img width="567" alt="terminal" src="https://github.com/Homebrew/brew.sh/assets/231978/d8cfe734-2104-4a41-ad96-5844a66b854b">

**Comment by SMillerDev** [comment]
Yeah, not much we can do about that.

**Comment by msokk** [comment]
@SMillerDev roger, I tried reporting it to Google Adsense through https://support.google.com/google-ads/answer/4581420?hl=en#ts=6006595&hl=en&dark=0&service_configuration=&visit_id=638508497726289763-3545719244&rd=1&hl=en&dark=0&service_configuration=&visit_id=638508497726289763-3545719244&hl=en&dark=0&service_configuration=&visit_id=638508497726289763-3545719244
but their form errors out with `Contact Flows RPC has errors: Code: FORM_NOT_FOUND` 🥲 Maybe it works for you?

We will be blocking phishing domain on our network at least.

**Comment by alex** [comment]
Phishing pages can be reported to Google with https://safebrowsing.google.com/safebrowsing/report_general/

**Comment by FranckPoingt** [comment]
Any idea what it does?

**Comment by Bo98** [comment]
Not seeing anything pop up from that domain on my end.
