### ISSUE TITLE
Missing IPv6 Connectivity

### ISSUE THREAD

**Issue by n-thumann** [Homebrew/brew.sh#1025]
This is a reopening of https://github.com/Homebrew/brew.sh/issues/623, because it has been closed until GitHub Pages support IPv6. They do since https://github.blog/changelog/2021-09-30-enabling-ipv6-support-for-github-pages/.
Other subdomains of brew.sh seem to already have AAAA records set, but could you also add them to brew.sh?

Functionally, it seems to be working:
```
➜  ~ curl -s --resolve brew.sh:443:2606:50c0:8000::153 https://brew.sh/ | grep "<title>"
    <title>Homebrew — The Missing Package Manager for macOS (or Linux)</title>
```

**Comment by Bo98** [comment]
Done. May take some time to propagate globally.

**Comment by carlocab** [comment]
```
❯ dig brew.sh @1.1.1.1 AAAA +short
2606:50c0:8000::153
2606:50c0:8001::153
2606:50c0:8002::153
2606:50c0:8003::153
```
Nice.

**Comment by n-thumann** [comment]
Awesome, thanks for the quick fix!
