### ISSUE TITLE
Remove the .vscode folder

### ISSUE THREAD

**Issue by Bashamega** [Homebrew/brew.sh#1069]
Hello:)

The `.vscode` folder should not be committed because it is depending on the user preference.

I would like to create a pr that will ignore the `.vscode` folder

**Comment by MikeMcQuaid** [comment]
> The `.vscode` folder should not be committed because it is depending on the user preference.

No, we only commit settings that provide the standard style for Homebrew and we prioritise making it easier for developers to get sorted.
