### ISSUE TITLE
http://caskroom.io/search/ 404

### ISSUE THREAD

**Issue by brandonkal** [Homebrew/brew.sh#247]
The search link on caskroom.io leads to a non-existing page.

**Comment by MikeMcQuaid** [comment]
That website is not controlled by Homebrew or Homebrew Cask.

**Comment by brandonkal** [comment]
How devious. I thought I read somewhere that Homebrew Cask maintained a searchable website.

**Comment by reitermarkus** [comment]
The old Homebrew Cask website had that functionality, but this was dropped when it was merged into `brew.sh`.
