### ISSUE TITLE
Better homebrew-cask landing page

### ISSUE THREAD

**Issue by szhu** [Homebrew/brew.sh#301]
If you [search "homebrew cask"](https://www.google.com/search?q=homebrew+cask), the ad-laden caskroom.io shows up as the top result. (NB for those who are unaware: caskroom.io is now controlled by an unaffiliated third-party.)

Two observations/questions:

- Is there something that can be done to take that site down? They don't do anything super malicious but that doesn't mean it will stay that way. For example, is there anything we can claim based on the fact that they are misrepresenting themselves as the official project website?

- Obviously one of the reasons why the site is ranked first is because it used to be the official site, but I think another reason why Google keeps it there is because it provides utility that brew.sh does not. For example, people who only want to use (and not contribute casks to) homebrew cask who land on brew.sh might have a hard time figuring out exactly what the tool is about.

I know it's easy to say "we can't do anything about this" and just close this issue. I'd like to request this issue remain open for a bit (ideally until the site is no longer the number 1 search result) to indicate that it is an issue that people will continue to run into -- perhaps someone will come along who has a solution to this, in which case this issue could be a centralized place to talk about it.

**Comment by MikeMcQuaid** [comment]
> * Is there something that can be done to take that site down?

As far as I can tell: no.

> * but I think another reason why Google keeps it there is because it provides utility that brew.sh does not

Google doesn't decide based on things like that. It's based on PageRank and SEO. 

> I know it's easy to say "we can't do anything about this" and just close this issue. I'd like to request this issue remain open for a bit (ideally until the site is no longer the number 1 search result) to indicate that it is an issue that people will continue to run into -- perhaps someone will come along who has a solution to this, in which case this issue could be a centralized place to talk about it.

Sorry, I disagree. Until there's something actionable (i.e. that could turn into a PR) I'm 👎 on having an open issue. Homebrew/homebrew-cask may want to keep this around there to discuss but it's not an issue with this website.

**Comment by szhu** [comment]
> Google doesn't decide based on things like that. It's based on PageRank and SEO.

Sorry, wasn't meaning to suggest that Google actively does that. I was just guessing  why people still link and click through to caskroom.io rather than brew.sh (aka the root cause of why it has good PageRank and SEO).


Also, was suggesting something actionable -- perhaps Cask could be more prominently featured on brew.sh? There should probably be an explainer of the differences between `brew install` and `brew cask install` -- I've gotten a lot of people to use both and I've seen that it's something that not clearly explained to new users.

I'm imagining something like a table to compare the two, or a two-step tutorial to show people how to figure out which tool the software they want to install is available on.

**Comment by MikeMcQuaid** [comment]
I'm open to PRs to improve/change the homepage; suggested code changes are easier to discuss than prose.
