### ISSUE TITLE
When selected russian language search not working

### ISSUE THREAD

**Issue by maxlanser** [Homebrew/brew.sh#477]
If I choose Russian on the site, the search does not find any packages.
In English everything works without problems.

**Comment by MikeMcQuaid** [comment]
@maxlanser the language scopes just check the homepage in that language. We'd consider a PR to tweak that behaviour.

**Comment by maxlanser** [comment]
> We'd consider a PR to tweak that behaviour.

I do not quite understand

**Comment by MikeMcQuaid** [comment]
@maxlanser The current behaviour is intentional but if you wish to change it you can make a GitHub pull request to this repository to change the code and we'll take a look at that. Thanks!
