### ISSUE TITLE
Installation instructions no longer valid on latest macOS

### ISSUE THREAD

**Issue by defx** [Homebrew/brew.sh#489]
## What you were trying to do (and why)

Install brew according to instructions on brew.sh

## What happened (include command output)

On macOS Catalina, **/usr/local** requires sudo. I believe this has been the case since High Sierra, so the installation instructions are no longer valid. 

## What you expected to happen

Installation happens without sudo (according to the docs)

## Step-by-step reproduction instructions

1. `cd ~/usr/local`
2. `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"`

**Comment by MikeMcQuaid** [comment]
> Installation happens without sudo (according to the docs)

Installation requires sudo. This is intentional.

**Comment by defx** [comment]
@MikeMcQuaid That's fine, but the instructions still need updating...

<img width="668" alt="Screenshot 2020-05-18 at 17 38 09" src="https://user-images.githubusercontent.com/4522676/82237959-662d1f80-992e-11ea-9aae-6c5bfb8c46c8.png">

**Comment by defx** [comment]
@MikeMcQuaid Ok, but the command doesn't include it, and running it with sudo exits with "Don't run this as root!". Wouldn't you agree that the instructions in this case aren't useful?

**Comment by MikeMcQuaid** [comment]
You're the first person I've heard of that has this particular issue. Homebrew has millions of users. I can't see how the instructions can be improved.
