### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by chjohn22** [Homebrew/brew.sh#510]
### Remove Google Analytics

If you must have an analytics system, might I suggest either:

    Plausible: https://plausible.io (offers a 50% discount for FOSS projects)
    Goatcounter: https://goatcounter.com
    Matomo: https://matomo.org
    Fathom: https://usefathom.org

These solutions are all well-tested and open-source. This, of course, means they
can be independently audited for privacy and security. Instead of using a proprietary
nonfree system such as Google Analytics, perhaps we could work together to replace
it with something slightly more ethical?

Furthermore, the majority of privacy features in evergreen browsers block Google
Analytics from being run. I can not say the same for solutions such as Plausible,
which suggests they are trusted for their privacy by independent persons.

If you need any more information, please contact me!

**Comment by MikeMcQuaid** [comment]
Passing on this for now. I don't see the benefit so long as Homebrew itself uses Google Analytics.

**Comment by MikeMcQuaid** [comment]
> Instead of using a proprietary nonfree system such as

We primarily target macOS: a proprietary non-free system. This should be a hint.

**Comment by chjohn22** [comment]
@MikeMcQuaid I understand this, but it would still be favorable to switch to a selfhosted alternative to get the necessary insights for your team. Matomo is very performant and easy to selfhost. I respect your open communication in this matter and the detailed explanation of the collected data in https://docs.brew.sh/Analytics. It is still a good idea to keep the alternatives in mind for possible changes in the future.

**Comment by MikeMcQuaid** [comment]
> but it would still be favorable to switch to a selfhosted alternative

It would be not. We do not wish to host our own analytics platform.



> It is still a good idea to keep the alternatives in mind for possible changes in the future.

Yup, we will 👍🏻. It's on my list to investigate if we can replace Google Analytics in Homebrew with another (hosted, free) platform that stores less data. If/when we do that: we'll likely move analytics from here too.

**Comment by resynth1943** [comment]
Hey Mike, hope you don't mind me jumping in. I would like to share some more information with you, so you can make an informed decision.  

> Yup, we will 👍🏻. It's on my list to investigate if we can replace Google Analytics in Homebrew with another (hosted, free) platform  

There are free alternatives, but you must remember: when you are using an ethical Analytics platform, the business model is conceptually different.  

As FOSS alternatives aim to sell the analytics product, not the user, there aren't too many free ethical platforms.  One of the free ones is [Goatcounter](https://Goatcounter). I rely on them to host analytics for [my website](https://resynth1943.net).

 Feel free to look [here for a demo of Goatcounter](https://resynth1943.goatcounter.com). I would definitely encourage you to make your statistics public, as publicity is crucial to the social aspect of FOSS. 

 ---  
 
Another platform I would definitely recommend is [Plausible](https://plausible.io).

## Hosted

*These solutions are not self-hosted.*

If you want some pricing information, see the table below.

|         | Plausible (annually) | Plausible (monthly) | Fathom | Matomo           | GoatCounter    |
|---------|----------------------|---------------------|--------|------------------|----------------|
| 50K/mo  | *$2/mo*              | $3/mo               | $14/mo | $23.8/mo (£19)   | *Free*         |
| 100K/mo | *$4/mo*              | $6/mo               | $14/mo | $36.4/mo (£29)   | *Free*         |
| 200K/mo | *$12/mo*             | $18/mo              | $24/mo | $61/mo (£49)     | $16/mo (€15)   |
| 500K/mo | *$12/mo*             | $18/mo              | $34/mo | $111.7/mo (£89)  | $33.7/mo (€30) |
| 1M/mo   | *$12/mo*             | $18/mo              | $54/mo | $174.4/mo (£139) | $33.7/mo (€30) |

~~Plausible really is tempting.~~ 

I have been in touch with the Plausible developers, and here is their response to an email asking about their pricing for FOSS stuff:

> Thanks for reaching out! Yes, we do have a discount for other open source projects. 50% off on all plans. How does that sound?
>
> Let me know what your project is and I can send you a coupon you can use when you're subscribing to a paid plan.

As such, I have cut the prices for Plausible in half. If anyone would like to take them up on this offer, you can contact them using [this web form.](https://plausible.io/contact)

---

How much funding does the Homebrew project receive? $2/mo (or $4/mo, depending on your needs) for an analytics solution is incredibly cheap, and Plausible is a very mature platform.

[We also use Plausible for our project, ReverseEagle.](https://plausible.io/reverseeagle.org). Please take a look, and see what you think!

I would love to chat with you further on this? Hopefully you don't lock this issue, as seems to be the case on GitHub. You seem to be respectable people who want to listen, so I'm hoping we can work something out!

<3 Resynth

**Comment by MikeMcQuaid** [comment]
Unfortunately locking this because it's now attracting comments from people trying to sell their products.
