### ISSUE TITLE
Guidance notes and script require update

### ISSUE THREAD

**Issue by rob-nash** [Homebrew/brew.sh#613]
The [release notes](https://brew.sh/2020/12/01/homebrew-2.6.0/) for 2.6.0 explain the following regarding /opt dir.

<img width="617" alt="Screenshot 2021-03-22 at 16 10 45" src="https://user-images.githubusercontent.com/81155150/112021475-3db31a80-8b29-11eb-821d-1d576b155c06.png">

The script on your homepage installs to /usr/local and the guidance there is still discussing /usr/local as the dir of choice.

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

**Comment by MikeMcQuaid** [comment]
This is done by the script.
