### ISSUE TITLE
IPv6 Connectivity

### ISSUE THREAD

**Issue by mkg20001** [Homebrew/brew.sh#623]
On IPv6-only networks it is impossible to access brew.sh due to lack of IPv6 address.

```
dig brew.sh @1.1.1.1 AAAA +short # returns nothing
```

Would it be possible to provide IPv6 connectivity for brew?

(If not opposed to using it for any reason, cloudflare is a good quick-fix)

**Comment by MikeMcQuaid** [comment]
Does GitHub Pages provide IPv6 connectivity?

**Comment by mkg20001** [comment]
They don't seem to https://github.community/t/cannot-reach-any-github-io-page-via-ipv6/10310

**Comment by MikeMcQuaid** [comment]
Sorry, passing on this until GitHub Pages supports it.

**Comment by mkg20001** [comment]
It hasn't happened for 2 years. I just added cloudflare to my domain. mkg20001.io is also using github pages.
