### ISSUE TITLE
zsh: command not found: brew

### ISSUE THREAD

**Issue by olegKusov** [Homebrew/brew.sh#721]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/28058268/139556864-1c9aa77e-b5fb-4b6c-84ba-3a8d20ce3966.png">
I installed homebrew on macOS with this command and it shows that brew not found.

**Please, add additional steps to installation guide on homepage.**

There is "NEXT STEPS shown on command line, it should show something like this

==> Next steps:
- Add Homebrew to your PATH in /Users/$USER/.zprofile:
    echo 'eval $(/opt/homebrew/bin/brew shellenv)' >> /Users/$USER/.zprofile
    eval $(/opt/homebrew/bin/brew shellenv)
    
" (https://stackoverflow.com/questions/36657321/after-installing-homebrew-i-get-zsh-command-not-found-brew). 

**The problem is that users don't read command line. I clear my command line after installation immediately**

**Comment by MikeMcQuaid** [comment]
> The problem is that users don't read command line.

This is a user problem not a Homebrew one.
