### ISSUE TITLE
Symlink Location is Platform-Dependent

### ISSUE THREAD

**Issue by ssardegna** [Homebrew/brew.sh#841]
On the brew homepage, the text states:

https://github.com/Homebrew/brew.sh/blob/6d812af16121e3f5bada3847f8428c5e3f8f1475/_data/locales/en.yml#L8

However, per the man page, the prefix for the location where symlinks are created is platform dependent (i.e. not always `/usr/local`):

```bash
--prefix [--unbrewed] [--installed] [formula ...]
       Display Homebrew´s install path. Default:

       •   macOS Intel: /usr/local

       •   macOS ARM: /opt/homebrew

       •   Linux: /home/linuxbrew/.linuxbrew
```

This behavior is confirmed when installing on an M1 Mac.

**Comment by MikeMcQuaid** [comment]
The examples are easier to understand when we refer to a single prefix. We could add a `(on macOS Intel)` or something if desired.

**Comment by ReagentX** [comment]
Apple no longer sells laptops with Intel CPUs and it won't be long until the rest of the line follows suit. Using the Intel path provides users with outdated information.

**Comment by MikeMcQuaid** [comment]
@ReagentX It will be a long time until the majority of Homebrew users are on ARM. There's a bunch of software still not ported and, as a result, a bunch of users still using `/usr/local` on ARM for the Intel binaries under Rosetta 2.

If you have a concrete suggestion on how to improve this: please make a PR.
