### ISSUE TITLE
You have already activated i18n 1.8.11, but your Gemfile requires i18n 0.9.5. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)

### ISSUE THREAD

**Issue by zouchengli** [Homebrew/brew.sh#845]
/Users/chengli.zou/.gem/ruby/3.0.0/gems/bundler-2.3.4/lib/bundler/runtime.rb:309:in `check_for_activated_spec!': You have already activated i18n 1.8.11, but your Gemfile requires i18n 0.9.5. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
	from /Users/chengli.zou/.gem/ruby/3.0.0/gems/bundler-2.3.4/lib/bundler/runtime.rb:25:in `block in setup'
	from /Users/chengli.zou/.gem/ruby/3.0.0/gems/bundler-2.3.4/lib/bundler/spec_set.rb:136:in `each'
	from /Users/chengli.zou/.gem/ruby/3.0.0/gems/bundler-2.3.4/lib/bundler/spec_set.rb:136:in `each'
	from /Users/chengli.zou/.gem/ruby/3.0.0/gems/bundler-2.3.4/lib/bundler/runtime.rb:24:in `map'
	from /Users/chengli.zou/.gem/ruby/3.0.0/gems/bundler-2.3.4/lib/bundler/runtime.rb:24:in `setup'
	from /Users/chengli.zou/.gem/ruby/3.0.0/gems/bundler-2.3.4/lib/bundler.rb:151:in `setup'
	from /Users/chengli.zou/.gem/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
	from /Users/chengli.zou/.gem/ruby/3.0.0/gems/jekyll-4.2.1/exe/jekyll:11:in `<top (required)>'
	from /Users/chengli.zou/.gem/ruby/3.0.0/bin/jekyll:25:in `load'
	from /Users/chengli.zou/.gem/ruby/3.0.0/bin/jekyll:25:in `<main>'

**Comment by mistydemeo** [comment]
Try adding `bundle exec` to the command, like the error suggests.

**Comment by zouchengli** [comment]
> Try adding `bundle exec` to the command, like the error suggests.

![image](https://user-images.githubusercontent.com/27568522/148155062-ebb39a74-d3f4-4342-b127-806146fcfdf3.png)

**Comment by mistydemeo** [comment]
Try `bundle exec jekyll serve`.

**Comment by zouchengli** [comment]
> Try `bundle exec jekyll serve`.

![image](https://user-images.githubusercontent.com/27568522/148164613-c3f35c65-c1af-4248-9b01-71dda1963715.png)

**Comment by zouchengli** [comment]
https://github.com/github/pages-gem/issues/752

You must execute this command before trying: 

`bundle add webrick`

![image](https://user-images.githubusercontent.com/27568522/148165640-cb09f66f-e251-49ef-a072-3fd3d97d444c.png)
