### ISSUE TITLE
Preloading HSTS for `brew.sh`

### ISSUE THREAD

**Issue by lgarron** [Homebrew/brew.sh#873]
Given that `brew.sh` is a user-facing site, I think it would be great to send an HSTS header to preload the site (and all subdomains) for HTTPS enforcement in browsers: https://hstspreload.org/?domain=brew.sh

Assuming all subdomains are already using HTTPS, `brew.sh` can send a header of `Strict-Transport-Security: max-age=63072000; includeSubDomains; preload` to enable preloading (at which point it can be submitted to the link above).

Since `brew.sh` is hosted via GitHub Pages, HSTS support is available — but at the moment it would need to be enabled by GitHub staff. We can arrange that internally.

**Comment by MikeMcQuaid** [comment]
> Since `brew.sh` is hosted via GitHub Pages, HSTS support is available — but at the moment it would need to be enabled by GitHub staff. We can arrange that internally.

Sounds good, thanks!

**Comment by lgarron** [comment]
> > Since `brew.sh` is hosted via GitHub Pages, HSTS support is available — but at the moment it would need to be enabled by GitHub staff. We can arrange that internally.
> 
> Sounds good, thanks!

We've gone ahead and done that!

I've followed up with the submission:
<img width="985" alt="Screen Shot 2022-04-01 at 13 30 01" src="https://user-images.githubusercontent.com/248078/161337038-38d9da76-46ee-4323-abe0-edb71d3767bc.png">
