### ISSUE TITLE
Incorrect zsh completions instructions

### ISSUE THREAD

**Issue by Undre4m** [Homebrew/brew.sh#900]
Instructions under [Configuring Completions in zsh](https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh) correctly prompt users to load _zsh/site-functions_ path into **FPATH** and calling _compinit_ at `~/.zshrc`.
<img width="659" alt="image" src="https://user-images.githubusercontent.com/19176718/197370518-5c06b079-0963-4eaa-8530-9cd22b5c072d.png">

However, for **Oh My Zsh** users, since completions are automatically initialized by **OMZ** (when sourcing _oh-my-zsh.sh_), users are **INSTEAD** instructed to update **FPATH** at `~/.zprofile` as to make completions available before _compinit_ is called.
<img width="670" alt="image" src="https://user-images.githubusercontent.com/19176718/197370448-f056e6aa-0537-45fb-bbdd-46682d8809ad.png">

This won't work on **non-login** shells, as `$ZDOTDIR/.zprofile` is **only** sourced for **login** shells by default: [Zsh Startup/Shutdown Files](https://zsh.sourceforge.io/Doc/Release/Files.html#Files)

> Commands are then read from `$ZDOTDIR/.zshenv`. If the shell is a **login** shell, commands are read from `/etc/zprofile` and then `$ZDOTDIR/.zprofile`. Then, if the shell is **interactive**, commands are read from `/etc/zshrc` and then `$ZDOTDIR/.zshrc`.

For completions to work for non-login **interactive** Zshells **FPATH** should be updated at `$ZDOTDIR/.zshrc`, **before** OMZ is initialized (`source $ZSH/oh-my-zsh.sh`). Instructions should be corrected to reflect this. Install script [Next steps instructions](https://github.com/Homebrew/install/blob/master/install.sh#L987) should also be corrected.

**Comment by MikeMcQuaid** [comment]
Can you submit a pull request to https://github.com/Homebrew/brew/tree/master/docs to make your requested changes? Thanks!
