### ISSUE TITLE
Acknowledge /opt/homebrew for macOS on ARM

### ISSUE THREAD

**Issue by colindean** [Homebrew/brew.sh#933]
https://github.com/Homebrew/brew.sh/blob/d5b89ed3003787776f262c7479868e0d4eb012d3/_data/locales/en.yml#L8 only includes the Intel path. I think it'd be a good idea to do one or more of:

1. include `/opt/homebrew` in there for macOS ARM
2. remove the Intel path from there and call it "the Homebrew installation prefix"
3. put the paths in a table behind a `<details>` or something, consider including Linuxbrew default path, too

Hard this is that this may require updating many translations files. I can probably handle a handful of them or any that are obvious, but I'd prefer to go the table route because that could eliminate the need for a localized string to be added.

**Comment by MikeMcQuaid** [comment]
> 2\. remove the Intel path from there and call it "the Homebrew installation prefix"

I'm game with this. This stuff doesn't need to be comprehensive.



> Hard this is that this may require updating many translations files.

We just can't do so really. The translations will catch up when the community updates it.



> but I'd prefer to go the table route because that could eliminate the need for a localized string to be added.

That'll still require us to adjust the current localisations first.

**Comment by colindean** [comment]
Not ready to push up the code yet, but here's something I've done up for the table in no. 3:

Details closed:

![Screenshot 2023-02-09 23 25 31](https://user-images.githubusercontent.com/197224/217953415-a99894ab-349a-491c-a314-225539a8f829.png)

Details open:

![Screenshot 2023-02-09 23 25 43](https://user-images.githubusercontent.com/197224/217953411-05c54252-12ac-4eaa-91b5-5a64c544db20.png)

I also had another revision that didn't combine the rows for Linux, and I preferred it combined. I also thought about putting the archs on the columns and OSes on the rows and might go in that direction.

**Comment by colindean** [comment]
I did that a lot sooner than I thought I'd get to it. 

![Screenshot 2023-02-09 23 31 41](https://user-images.githubusercontent.com/197224/217954172-67aa5cb7-b99d-464b-8818-ee8355e2393d.png)

Could go either way.

**Comment by colindean** [comment]
I put up what I've got so far in #939. 

How have we handled adding new i18n keys? This will get us emails of everyone's that's touched one of the l10n files to do a "hey, go update this" nudge email...?

```sh
fd --exclude=_data/locales/en.yml --full-path _data/locales --exec git log -n 2 --pretty="format:%ae%n" -- {} | sort -u | grep -v noreply | grep -v "^$"
```

**Comment by MikeMcQuaid** [comment]
@colindean Don't email folks. Just leave it and it'll be updated over time. Doesn't matter if there's a little inconsistency. This is not an urgent change.
