### ISSUE TITLE
Translations for Serbian

### ISSUE THREAD

**Issue by kizule** [Homebrew/brew.sh#944]
Hello,
this isn't actually a bug report, but a question. I'm hoping there won't be any problem. :)

I just found that https://brew.sh is having translations in Serbian language.
Current translation is on Cyrillic, but Serbian language is having Cyrillic and Latin script.

How I can create translations on Serbian Latin as well?

Thank you for your understanding!

Best regards,
Zoran

**Comment by EricFromCanada** [comment]
Based on my limited understanding of [BCP 47 / RFC 5646](https://www.rfc-editor.org/info/bcp47), the file `sr.yml` should be renamed to `sr-cyrl.yml` and a new Serbian Latin translation can be added as `sr-latn.yml`. If you can file a pull request that does so (and updates both to the current [en.yml](https://github.com/Homebrew/brew.sh/blob/master/_data/locales/en.yml)), that would be great!

**Comment by kizule** [comment]
Thank you so much for informations!

Yeah, I know about BCP 47, but I didn't know what jekyll is using exactly + as I'm volunteering on Wikipedia, I'm used to some ISO format with sr-ec (Serbian Cyrillic), sr-el (Serbian Latin) and sr (fallback in MediaWiki to sr-ec).

I'd like to make a pull request for updating existing translations on Serbian Cyrillic + add translations in Serbian Latin, that's why I've created this.

**Comment by kizule** [comment]
I'll go ahead and make a pull request, thanks for reminding me. :)

**Comment by MikeMcQuaid** [comment]
Will happily review a PR here, thanks!
