### ISSUE TITLE
Search opens a flashing modal

### ISSUE THREAD

**Issue by MarjaE2** [Homebrew/brew.sh#970]
1. open https://formulae.brew.sh/
2. Click the search bar, type search terms
3. The results open in a modal.
4. The modal flashes 3 times, 1 as it loads without results, 2 as a long list appears, 3 as some results disappear.
5. The modal also flashes as users key up or down the list.

https://github.com/Homebrew/brew.sh/assets/12875862/2687fa5a-4b1d-425f-8090-3a73afccca06

Screen recording in Firefox in Troubleshoot Mode.

**Comment by mistydemeo** [comment]
I don't see flashing in the video you included; could you describe in more detail what exactly you're seeing, and what web browser you use?

**Comment by MarjaE2** [comment]
It is Firefox 115 in troubleshoot mode. For me, the video shows flashing at 2 seconds, 3 seconds, 4 seconds, twice at 5 seconds, and 6 seconds.

**Comment by SMillerDev** [comment]
If by "flashing" you mean "something changes in the screen" then yes, when the content updates it does that.

**Comment by MarjaE2** [comment]
It's fast, it's intense, and it can be more than 1/second.

**Comment by SMillerDev** [comment]
I've tried replaying the video at different speeds and different sizes, but I can not spot any flashing. I'd also like to point out that Homebrew only changed the colours of a default Algolia integration, so it would be good to see if it also happens on https://www.algolia.com/doc/, and if so report it to Algolia instead.
