### ISSUE TITLE
Implement SRI, says Moz Observatory

### ISSUE THREAD

**Issue by colindean** [Homebrew/brew.sh#973]
Quoth Mozilla Observatory, which [gives brew.sh](https://observatory.mozilla.org/analyze/brew.sh) a **D** rating as of [d60d598](https://github.com/Homebrew/brew.sh/commit/d60d598a608541d2e7bca0590f14853f85dc4e90):

Test | Pass | Score | Reason | Info
-- | -- | -- | -- | --
Subresource Integrity | ❌   | -5 | Subresource Integrity (SRI) not implemented, but all external scripts are loaded over HTTPS | Subresource Integrity protects against JavaScript files and stylesheets stored on content delivery networks (CDNs) from being maliciously modified.

<https://infosec.mozilla.org/guidelines/web_security#subresource-integrity> has instructions.

**Comment by colindean** [comment]
It looks like we have _some_ SRI in place already but need to add it one other:

https://github.com/Homebrew/brew.sh/blob/d60d598a608541d2e7bca0590f14853f85dc4e90/_layouts/base.html#L158-L165

**Comment by colindean** [comment]
There's an issue open upstream about this: https://github.com/algolia/docsearch/issues/1561

**Comment by colindean** [comment]
Keep open. I have a plan that might involve moving that in-page js to a file.

**Comment by MikeMcQuaid** [comment]
Don't think we need to keep this issue open given the PR.
