### ISSUE TITLE
Brew Bot Image not rendered within docs

### ISSUE THREAD

**Issue by oregonpillow** [Homebrew/brew.sh#981]
At the top of https://docs.brew.sh/Brew-Test-Bot and https://docs.brew.sh/Homebrew-on-Linux you'll see that the picture is not rendered despite the src image being valid. Maybe a permission issue?

![Screenshot 2023-08-27 at 12 45 02](https://github.com/Homebrew/brew.sh/assets/53374403/2ff3dac1-6409-4728-9196-741113d7fbc4)

**Comment by SMillerDev** [comment]
Might be related to recent changes from @colindean

**Comment by brareme** [comment]
_(This is Colin working from Brigette's computer)_

We didn't catch that [docs.brew.sh pulls homebrew/brew.sh as a theme](https://github.com/Homebrew/brew/blob/b0c54058f30af1256114c787c8336cce9a8cc5d9/docs/_config.yml#L4), so it thus inherits its CSP:

```sh
% curl -s https://docs.brew.sh | grep Content-Security-Policy
    <meta http-equiv="Content-Security-Policy"
```

@EricFromCanada's solution in Homebrew/brew#15917 is adequate: the images are fine coming from the same subdomain anyway, although they'd likely be cached from www/brew.sh.

If we encounter another problem like this in another subdomain's code, I'll expand the CSP to include brew.sh for images.
